### ISSUE TITLE
Can it run on stm32F429

### ISSUE THREAD

**Issue by eEmbedded-development** [yhzhang0128/egos-2000#10]

**Comment by eEmbedded-development** [comment]
Can it be ported to stm32F429 and run in the above environment

**Comment by eEmbedded-development** [comment]
Can it be ported to stm32F429 and what environment does it need to run in

**Comment by eEmbedded-development** [comment]
How can I add the stm32F429 board to the Egos-2000 operating system to support it

**Comment by yhzhang0128** [comment]
Please refer to [this discussion thread](https://github.com/yhzhang0128/egos-2000/discussions/7). The porting process for different hardware platform is similar.

**Comment by eEmbedded-development** [comment]
我阅读了egos-2000的操作系统，然后大概是这样的，earth-grass-app，发现你里面用了qemu的仿真器可以跑，还有arty7，然后我有疑惑的是，移到stm32上面，我该怎么做，找不到思路，移植它需要改什么配置。

我想问一个问题，我要在什么环境上面跑比较合适，我打算使用keil 5的工具进行移植可行吗








I have read the operating system of EGOS-2000 and found that it is like this: earth grass app. I found that you have used a QEMU emulator that can run, as well as Arty7. However, I have some doubts about what to do when moving to STm32. I cannot find a solution, and what configuration changes are needed to port it.




I would like to ask a question, which environment is more suitable for me to run in, and do I plan to use the Keil 5 tool for porting









谢灿杰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yhzhang0128/egos-2000"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月3日(星期一) 上午9:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yhzhang0128/egos-2000] Can it run on stm32F429 (Issue #10)





 
Please refer to this discussion thread. The porting process for different hardware platform is similar.

**Comment by yhzhang0128** [comment]
感谢你的问题。我查了下stm32是ARM架构的，并非RISC-V，所以感觉跑egos-2000需要的改动并不少。我对ARM和stm32了解的都不多，但如果你有足够的时间想要用stm32跑egos-2000，我们可以在这个thread下面继续交流。

作为第一步，你可以尝试在stm32上跑一个简单的程序测试两件事：(1) printf输出; (2) 中断处理，包括时钟中断和内存访问异常。如果这两个都能work，那么移植egos-2000就是有希望的。这里可能会用到你说的Keil 5工具。

张云昊

Thank you for your question. I found that stm32 is based on ARM instead of RISC-V so that porting egos-2000 onto stm32 may take some efforts. I am not very familiar with ARM and stm32, but if you have enough time on this project, I am happy to continue the discussion under this thread and learn about ARM and stm32.

As a first step, you may try 2 things on stm32: (1) printf() function; (2) interrupt handling, including timer and memory exception. If both can work, then it is promising to port egos-2000 onto stm32. You may need the Keil5 tool at this point.

Yunhao

**Comment by eEmbedded-development** [comment]
(1) printf输出; (2) 中断处理，包括时钟中断这两个在stm32上面都可以跑，可以实现stm32的定时器中断，串口中断。定时器中断：当达到设置的时间时，会跳到指定的函数去执行相应的程序








谢灿杰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yhzhang0128/egos-2000"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月3日(星期一) 中午11:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yhzhang0128/egos-2000] Can it run on stm32F429 (Issue #10)





 
感谢你的问题。我查了下stm32是ARM架构的，并非RISC-V，所以感觉跑egos-2000需要的改动并不少。我对ARM和stm32了解的都不多，但如果你有足够的时间想要用stm32跑egos-2000，我们可以在这个thread下面继续交流。
 
作为第一步，你可以尝试在stm32上跑一个简单的程序测试两件事：(1) printf输出; (2) 中断处理，包括时钟中断和内存访问异常。如果这两个都能work，那么移植egos-2000就是有希望的。这里可能会用到你说的Keil 5工具。
 
张云昊
 
Thank you for your question. I found that stm32 is based on ARM instead of RISC-V so that porting egos-2000 onto stm32 may take some efforts. I am not very familiar with ARM and stm32, but if you have enough time on this project, I am happy to continue the discussion under this thread and learn about ARM and stm32.
 
As a first step, you may try 2 things on stm32: (1) printf() function; (2) interrupt handling, including timer and memory exception. If both can work, then it is promising to port egos-2000 onto stm32. You may need the Keil5 tool at this point.
 
Yunhao

**Comment by eEmbedded-development** [comment]
(1) printf输出; (2) 中断处理，包括时钟中断这两个在stm32上面都可以跑，可以实现stm32的定时器中断，串口中断。定时器中断：当达到设置的时间时，会跳到指定的函数去执行相应的程序




我老大让我移植操作系统到板子上面练手，我一开始拿到操作系统，一开始说实话蒙蒙的，然后就看着你的文档学习，和查看源码，然后还移植了网上很火的一个rt-thread操作系统到stm32上面去，但是它这个rt-thread-nano的教程很成熟，很快就移植成功了。对于egos-2000，现在想尝试移植它，却不知道如何下手


下面的链接是移植rt-thread-nano的文档
使用 MDK 移植 (rt-thread.org)








谢灿杰
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "yhzhang0128/egos-2000"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月3日(星期一) 中午11:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yhzhang0128/egos-2000] Can it run on stm32F429 (Issue #10)





 
感谢你的问题。我查了下stm32是ARM架构的，并非RISC-V，所以感觉跑egos-2000需要的改动并不少。我对ARM和stm32了解的都不多，但如果你有足够的时间想要用stm32跑egos-2000，我们可以在这个thread下面继续交流。
 
作为第一步，你可以尝试在stm32上跑一个简单的程序测试两件事：(1) printf输出; (2) 中断处理，包括时钟中断和内存访问异常。如果这两个都能work，那么移植egos-2000就是有希望的。这里可能会用到你说的Keil 5工具。
 
张云昊
 
Thank you for your question. I found that stm32 is based on ARM instead of RISC-V so that porting egos-2000 onto stm32 may take some efforts. I am not very familiar with ARM and stm32, but if you have enough time on this project, I am happy to continue the discussion under this thread and learn about ARM and stm32.
 
As a first step, you may try 2 things on stm32: (1) printf() function; (2) interrupt handling, including timer and memory exception. If both can work, then it is promising to port egos-2000 onto stm32. You may need the Keil5 tool at this point.
 
Yunhao

**Comment by yhzhang0128** [comment]
首先，根据你对printf和中断处理的描述，用stm32跑egos-2000应该是可行的。我估计我自己干的话需要1-3天时间，因为我之前移植到另一个RISC-V平台花了大概一天半。但你可能需要一点时间熟悉egos-2000才能完成这些修改。

如果printf和中断都不是问题，那么你可以修改`earth`下面的`cpu_intr.c`和`dev_tty.c`使得他们支持stm32的中断和print输出，这样egos-2000至少可以运行到这一行：https://github.com/yhzhang0128/egos-2000/blob/main/earth/earth.c#L40

你还需要修改Makefile使用arm编译器而非riscv编译器。这之后的修改基本都是修改下内存地址啥的。

最后，egos-2000设计的目的是教学而非商用，所以我并没有在设计时计划支持不同硬件平台。rt-thread作为一个商业系统确实应该可以通过修改一些配置直接跑在不同硬件上，但是egos-2000目前没有这个计划，在移植的时候需要对系统有更多的理解和修改。

**Comment by yhzhang0128** [comment]
以及，我的邮箱是yz2327@cornell.edu，你可以直接给我发邮件询问或者约online chat，我觉得你这个跑stm32的想法还挺有意思的。

**Comment by eEmbedded-development** [comment]
作者你人真的很好，感谢指导！向你学习


对于移植一个操作系统到stm32，我还是有点懵，我还需要具备哪些知识，毕竟第一次移植操作系统，我需要把源码阅读得比较详细是吧，我前段时间阅读了该操作系统的源码，earth的代码读起来不是很懂。今天刚看完了操作系统的核心知识，已经了解了操作系统。




谢灿杰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yhzhang0128/egos-2000"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月3日(星期一) 下午4:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yhzhang0128/egos-2000] Can it run on stm32F429 (Issue #10)





 
***@***.***，你可以直接给我发邮件询问或者约online chat，我觉得你这个跑stm32的想法还挺有意思的。

**Comment by yhzhang0128** [comment]
如果你已经了解stm32如何处理printf和中断，那么我建议你阅读以下4个文件
* earth/earth.S
* earth/earth.c
* earth/cpu_intr.c
* earth/dev_tty.c

然后你可以先把这4个文件改一改，跑在stm32上，其余的文件都可以先不看，这是移植的第一步。这一步成功之后，我们可以讨论后面的步骤，后面的步骤相对简单了

**Comment by eEmbedded-development** [comment]
可以在哪个环境上面跑呢？我在keil上面跑可以吗？这个earth.S在keil上面我不知道怎么跑，它好像就是一个调用main的，我直接将代码移植过去keil那边的主函数main就可以了？




谢灿杰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yhzhang0128/egos-2000"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月3日(星期一) 晚上10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yhzhang0128/egos-2000] Can it run on stm32F429 (Issue #10)





 
如果你已经了解stm32如何处理printf和中断，那么我建议你阅读以下4个文件
  
earth/earth.S
 
earth/earth.c
 
earth/cpu_intr.c
 
earth/dev_tty.c
  
然后你可以先把这4个文件改一改，跑在stm32上，其余的文件都可以先不看，这是移植的第一步。这一步成功之后，我们可以讨论后面的步骤，后面的步骤相对简单了

**Comment by yhzhang0128** [comment]
我没用过keil，但如果你熟悉keil的话应该可以。
`earth.S`的目的就是设置stack pointer然后调用main函数，你移植的时候只要能实现调用earth.c的main函数就好，不一定非要用`earth.S`. 而且你应该也无法直接用`earth.S`因为那里面的指令时RISC-V，但是stm32是ARM。

**Comment by eEmbedded-development** [comment]
作者你好，我移植到这一步



这些指令是RISC-V指令启用中断功能，不是很清楚怎样才能改成stm32的arm架构的


谢灿杰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yhzhang0128/egos-2000"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月4日(星期二) 上午9:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yhzhang0128/egos-2000] Can it run on stm32F429 (Issue #10)





 
我没用过keil，但如果你熟悉keil的话应该可以。
 earth.S的目的就是设置stack pointer然后调用main函数，你移植的时候只要能实现调用earth.c的main函数就好，不一定非要用earth.S. 而且你应该也无法直接用earth.S因为那里面的指令时RISC-V，但是stm32是ARM。

**Comment by eEmbedded-development** [comment]
作者你好，我移植到这一步



这些指令是RISC-V指令启用中断功能，不是很清楚怎样才能改成stm32的arm架构


谢灿杰
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "yhzhang0128/egos-2000"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月4日(星期二) 上午9:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yhzhang0128/egos-2000] Can it run on stm32F429 (Issue #10)





 
我没用过keil，但如果你熟悉keil的话应该可以。
 earth.S的目的就是设置stack pointer然后调用main函数，你移植的时候只要能实现调用earth.c的main函数就好，不一定非要用earth.S. 而且你应该也无法直接用earth.S因为那里面的指令时RISC-V，但是stm32是ARM。

**Comment by eEmbedded-development** [comment]
感谢您，作者，我慢慢看懂代码了




谢灿杰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yhzhang0128/egos-2000"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月3日(星期一) 晚上10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yhzhang0128/egos-2000] Can it run on stm32F429 (Issue #10)





 
如果你已经了解stm32如何处理printf和中断，那么我建议你阅读以下4个文件
  
earth/earth.S
 
earth/earth.c
 
earth/cpu_intr.c
 
earth/dev_tty.c
  
然后你可以先把这4个文件改一改，跑在stm32上，其余的文件都可以先不看，这是移植的第一步。这一步成功之后，我们可以讨论后面的步骤，后面的步骤相对简单了

**Comment by eEmbedded-development** [comment]
感谢您，作者，我慢慢看懂代码了


作者你好，你里面使用到的sd卡和文件系统是干什么的，我移植该操作系统可以先忽略掉sd卡和文件系统吗




谢灿杰
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "yhzhang0128/egos-2000"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月3日(星期一) 晚上10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yhzhang0128/egos-2000] Can it run on stm32F429 (Issue #10)





 
如果你已经了解stm32如何处理printf和中断，那么我建议你阅读以下4个文件
  
earth/earth.S
 
earth/earth.c
 
earth/cpu_intr.c
 
earth/dev_tty.c
  
然后你可以先把这4个文件改一改，跑在stm32上，其余的文件都可以先不看，这是移植的第一步。这一步成功之后，我们可以讨论后面的步骤，后面的步骤相对简单了

**Comment by eEmbedded-development** [comment]
感谢您，作者，我慢慢看懂代码了


作者你好，你里面使用到的sd卡和文件系统是干什么的，我移植该操作系统可以先忽略掉sd卡和文件系统吗




作者你好，可以请你帮我一下忙吗，该操作系统的目录列个移植提纲给我，哪些是必须要移植的（不可缺少）。哪些是可以不用移植的（不移植也不会影响）。




谢灿杰
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "yhzhang0128/egos-2000"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月3日(星期一) 晚上10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yhzhang0128/egos-2000] Can it run on stm32F429 (Issue #10)





 
如果你已经了解stm32如何处理printf和中断，那么我建议你阅读以下4个文件
  
earth/earth.S
 
earth/earth.c
 
earth/cpu_intr.c
 
earth/dev_tty.c
  
然后你可以先把这4个文件改一改，跑在stm32上，其余的文件都可以先不看，这是移植的第一步。这一步成功之后，我们可以讨论后面的步骤，后面的步骤相对简单了

**Comment by eEmbedded-development** [comment]
感谢您，作者，我慢慢看懂代码了


作者你好，你里面使用到的sd卡和文件系统是干什么的，我移植该操作系统可以先忽略掉sd卡和文件系统吗




作者你好，可以请你帮我一下忙吗，该操作系统的目录列个移植提纲给我，哪些是必须要移植的（不可缺少）。哪些是可以不用移植的（不移植也不会影响）。老师请帮我，谢谢老师，感激不尽




谢灿杰
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "yhzhang0128/egos-2000"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月3日(星期一) 晚上10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yhzhang0128/egos-2000] Can it run on stm32F429 (Issue #10)





 
如果你已经了解stm32如何处理printf和中断，那么我建议你阅读以下4个文件
  
earth/earth.S
 
earth/earth.c
 
earth/cpu_intr.c
 
earth/dev_tty.c
  
然后你可以先把这4个文件改一改，跑在stm32上，其余的文件都可以先不看，这是移植的第一步。这一步成功之后，我们可以讨论后面的步骤，后面的步骤相对简单了

**Comment by yhzhang0128** [comment]
SD卡驱动可以忽略，你在`earth/dev_disk.c`里面默认使用FLASH_ROM就可以。流程是这样的：`tools/mkfs.c`这个程序会在你的Linux/MacOS里面创建一个4MB的文件叫`disk.img`，然后这4MB的内容需要被加载到egos-2000内存的0x20800000这个地址。FLASH_ROM就是通过读取0x20800000到0x20C00000这段内存获取文件系统里的内容。

移植应该按照control flow，也就是程序执行的顺序移植
* earth/earth.c的main函数
* grass/grass.c的main函数
* apps/system/sys_proc.c的main函数
* grass/syscall.c的sys_invoke函数
* grass/scheduler.c的proc_syscall函数
* apps/system/sys_file.c的main函数
* apps/system/sys_dir.c的main函数
* apps/system/sys_shell.c的main函数

到这里系统就进入shell开始接受命令了，比如echo或者ls。

文件系统是需要的，因为从grass开始，所有elf格式可执行文件都需要通过文件系统读取。但是你应该可以直接把文件系统编译成arm，无需修改`lib/file`。

关于arm，你需要修改的是grass里面关于mepc的内容，你可以在grass目录下搜索`asm`，然后把那些汇编改成arm版本。以及stm32的内存可能跟我用的板子不一样，你可能需要修改lib/egos.h里面的内存地址，以及所有`lds`文件中的内存地址。在earth, grass和apps下一共有3个`lds`文件。
