### ISSUE TITLE
Bug due to integer promotion in `mtime_get`

### ISSUE THREAD

**Issue by red1bluelost** [yhzhang0128/egos-2000#13]
Take the function `mtime_get`
```c
static long long mtime_get() {
    int low, high;
    do {
        high = *(int*)(0x200bff8 + 4);
        low  = *(int*)(0x200bff8);
    }  while ( *(int*)(0x200bff8 + 4) != high );

    return (((long long)high) << 32) | low;
}
```

If `low` is a negative number (sign bit 31 is 1), then sign extension will occur on the return statement. C conversion rules state that a small sized integer is promoted to the larger type https://en.cppreference.com/w/c/language/conversion. The problem is demonstrated at this godbolt link: https://gary.godbolt.org/z/jxP4hKGMf.

For loading the individual components of the `long long`, these should probably be `unsigned`.

**Comment by yhzhang0128** [comment]
Thanks for reporting the issue. Indeed, I guess `low`, `hight` and the return value should all be unsigned. I will fix it tomorrow.

BTW, I was referencing this function: https://github.com/sifive/freedom-metal/blob/master/src/drivers/sifive_clic0.c#L420

**Comment by red1bluelost** [comment]
Thanks for fixing this in 114657dbcd8e7ed3a0658ba320b827be5e9b1fea :)
