### ISSUE TITLE
Earth and Grass Layer using the same stack pointer.

### ISSUE THREAD

**Issue by Vamber** [yhzhang0128/egos-2000#35]
I noticed both earth and grass layer's code uses 0x80003f80 as sp address.
I wonder what's the design intention behind this. Wouldn't this lead to the two process's stack content overriding each other ?

**Comment by yhzhang0128** [comment]
Thanks for the question. That was a poor and arbitrary design, which I have removed from the latest egos-2000.

In the current `main` branch, earth and grass are unified as a single executable and thus use only one stack, starting from 0x80400000 and growing down. See https://github.com/yhzhang0128/egos-2000/blob/main/earth/boot.s#L19

**Comment by Vamber** [comment]
Understood. Thank you so much !

Merging the grass and eath layer makes a lot sense, since neither needs software TLB or anything to be saved during context switch.

"the grass layer never returns to the earth layer and thus ...", this was an aha moment, because the context switching code is defined in earth.s, and all the driver code (tty, sd) are part of the earth code, but they are really executed through grass. Because there is not a earth process, everything kernel process is grass.
