### ISSUE TITLE
Can this project completely compile in the Win10 ?

### ISSUE THREAD

**Issue by Be997398715** [yhzhang0128/egos-2000#5]
It's really a great job, but my question is, limited by some environmental conditions, can all the compilation and running of this project be done on win10 only with gcc & riscv toolchain & qemu ? I am having trouble executing "make install" with mkfs and mkrom, hope for your reply.

**Comment by Be997398715** [comment]
Thank you for your reply. I am waiting for your further results.

**Comment by yhzhang0128** [comment]
I am currently spending my summer vacation in China and I don't have a Windows machine at my hand. I will work on this in early September after I go back to school. Thanks for your patience.

**Comment by yhzhang0128** [comment]
Hi there, I gave a few attempts today. I am able to run the RISC-V compiler from SiFive on Win10 and compile the binaries of egos-2000. However, I still fail to run their QEMU on my Win10.

In general, I feel like it is not a good idea to use Windows. Sorry about that and please consider to use a Linux or MacOS environment.

**Comment by yhzhang0128** [comment]
However, if you are willing to install and use [Docker](https://www.docker.com/) on your Windows, there is a simple way to run egos-2000. You can find my tutorial video here: https://youtu.be/hCDMnGGyGqM
