### ISSUE TITLE
Can't boot up using qemu

### ISSUE THREAD

**Issue by henry12338** [yhzhang0128/egos-2000#8]
When i use qemu to run egos-2000
it stuck in
```
cp build/release/earth.elf tools/qemu/qemu.elf
riscv64-unknown-elf-objcopy --update-section .image=tools/disk.img tools/qemu/qemu.elf
qemu-system-riscv32 -readconfig tools/qemu/sifive-e31.cfg -kernel tools/qemu/qemu.elf -nographic
```

**Comment by yhzhang0128** [comment]
Would you please give more details about your setup? Are you using Linux or MacOS? Are you using virtual machines or docker? And please make sure you don't have other `qemu-system-riscv32` or `riscv64-unknown-elf-objcopy` in your $PATH.

I know one similar situation. In that case, someone uses Win10 and runs a Ubuntu within VirtualBox. And QEMU gets stuck in Ubuntu. There seems to be some constraints about running QEMU in VirtualBox and I'm not sure whether this is your situation.

**Comment by yhzhang0128** [comment]
Hi there, did you manage to get around this issue? Would be great to learn about your experience.

Another possibility I met today is that, if you have an old version of MacOS, updating to the latest MacOS may help.
